plugins {
    id 'java'
    id 'net.minecraftforge.gradle' version '6.0.54'
}

version = mod_version
group = mod_group_id

base {
    archivesName = 'minecraft-but-you-cant-stop-walking'
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(21)
}

minecraft {
    mappings channel: 'official', version: minecraft_version

    runs {
        client {
            workingDirectory project.file('run')
            property 'forge.logging.console.level', 'info'
            mods {
                cantstopwalking {
                    source sourceSets.main
                }
            }
        }
    }
}

repositories {
    mavenCentral()
}

dependencies {
    minecraft "net.minecraftforge:forge:${minecraft_version}-${forge_version}"
}

tasks.named('processResources', ProcessResources) {
    def props = [
            minecraft_version: minecraft_version,
            forge_version: forge_version,
            mod_id: mod_id,
            mod_name: mod_name,
            mod_version: mod_version
    ]
    inputs.properties props
    filesMatching('META-INF/mods.toml') {
        expand props
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

jar {
    manifest {
        attributes([
                'Implementation-Title': mod_name,
                'Implementation-Version': mod_version,
                'Implementation-Vendor': 'pugplayzYT'
        ])
    }
}
