modLoader="javafml"
loaderVersion="[52,)"
license="MIT"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="pugplayzYT"
description='''
A client-side challenge mod that can force you to walk forward, jump forever, or both.
'''

[[dependencies.${mod_id}]]
modId="forge"
mandatory=true
versionRange="[${forge_version},)"
ordering="NONE"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="[${minecraft_version},1.21.2)"
ordering="NONE"
side="CLIENT"
